version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot_app
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge 